services:
  backend:
    build:
      context: ./backend
    container_name: pyji_backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: pyji_db
    restart: always
    environment:
      MYSQL_DATABASE: pyji_db
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    container_name: pyji_frontend
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  mysql_data: